FROM ubuntu:16.04
RUN apt-get update && apt-get -y upgrade && apt-get autoremove
RUN apt-get install -y --no-install-recommends \
   build-essential \
   cmake \
   cpio \
   curl \
   git \
   lsb-release \
   pciutils \
   python3.5 \
   python3-pip \
   python3-setuptools \
   sudo \
   libcpprest-dev
RUN mkdir /app && cd /app && \
    curl http://registrationcenter-download.intel.com/akdlm/irc_nas/15078/l_openvino_toolkit_p_2018.5.455.tgz \
    --output openvino.tgz && \
    tar xzf openvino.tgz
# installing OpenVINO dependencies
ARG INSTALL_DIR=/opt/intel/computer_vision_sdk
RUN cd /app/l_openvino_toolkit* && \
    ./install_cv_sdk_dependencies.sh
RUN cd /app/l_openvino_toolkit* && \
    sed -i 's/decline/accept/g' silent.cfg && \
    ./install.sh --silent silent.cfg && \
    rm -r /app
RUN /bin/bash -c "source $INSTALL_DIR/bin/setupvars.sh"
RUN echo "source $INSTALL_DIR/bin/setupvars.sh" >> /root/.bashrc
RUN cd /opt/intel/computer_vision_sdk/install_dependencies && bash install_NEO_OCL_driver.sh
WORKDIR /root
CMD ["/bin/bash"]
